mobile_id: on
host: resmap-stg-ilab.instedd.org
number_of_attempt_failed: 5

plugins:
  public_collection: on
  snapshot: on
  channels: on
  reminders: on
  alerts: on
  account_completeness: on
  fred_api: on
